spring:
#  aws에서 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awseb-e-tq2zb63met-stack-awsebrdsdatabase-ojr70xeihxdb.cvmic28o2x0d.ap-northeast-2.rds.amazonaws.com:3306/spring?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: seo
    password: 11

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: update
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

# 인증값은 github 업뎃 절대 하지 말것
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 11
            client-secret: 11
            scope:
              - email
              - profile

# data.sql 실행
#  sql:
#    init:
#      mode: always

jwt:
  issuer: appleg1418@gmail.com
  secret_key: 11