spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

# 인증값은 github 업뎃 절대 하지 말것
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:

            scope:
              - email
              - profile

# data.sql 실행
#  sql:
#    init:
#      mode: always

jwt:
  issuer: appleg1418@gmail.com
  secret_key: springboot