--INSERT INTO board (title, content, create_time, update_time) VALUES ('1', '111', NOW(), NOW());
--INSERT INTO board (title, content, create_time, update_time) VALUES ('2', '222', NOW(), NOW());
--INSERT INTO board (title, content, create_time, update_time) VALUES ('3', '333', NOW(), NOW());